[build]
  base    = "mrs-website"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_SEO_ENABLED = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"
